learning_rate: 0.0002
gradient_checkpointing: true
num_train_epochs: 3
logging_steps: 1
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
max_length: 2048
warmup_ratio: 0.03
lr_scheduler_type: "cosine_with_min_lr"
lr_scheduler_kwargs: {"min_lr_rate": 0.1}
output_dir: "./checkpoint/gpt-oss-20b-lora"
report_to: "tensorboard"
deepspeed: "ds_config.json"